### PR TITLE
Fix bad generated code with generic type hierarchies

### LINKED ISSUE #516: BadImageFormatException with abstract base class and two levels of derived classes with generic type parameter
This happens since 3.2.2  up to  3.2.4. In 3.2.1 it's working fine (using Fody 6.0.8).
The exception is raised when setting derivedB.Something in the code below. The issue does not happen when doing any of these:
- removing the generic type parameter
- removing the "middle" class DerivedA

The breaking change is commit 9a5d794d4c62ac607a62b4e0fde187bfb5ac1463.

I'll dig deeper into this, but just in case this does "ring a bell" to someone...

Here's the failing code, tested with .Net 4.7.2 and .Net Core 3.1:

```C#
using System.ComponentModel;

namespace FodyTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var derivedB = new DerivedB();
            derivedB.Something = "Bar";
        }
    }

    public class DerivedB : DerivedA<string>
    {
        public string Something { get; set; }
    }

    public class DerivedA<T> : Base<T> { }

    public class Base<T> : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    }
}
```

### PR DESCRIPTION
**Pull request by ltrzesniewski**
Fixes #516.

The first commit is unrelated (just some cleanup and test parallelization fix).

### CODE REVIEW

File: Tests/AssemblyToProcessTests.cs [hunk 1]
```diff
@@ -310,15 +311,49 @@ public void OnChangedMethodAttributeSuppressedDefaultMethodsWhenMethodNameIsNull
...
+            
+            // Issue #477
+            AssertInvoker(typeof(ClassWithGenericMiddleBase), nameof(ClassWithGenericMiddleBase.Property1), nameof(ClassWithGenericMiddleBase));
+            AssertInvoker(typeof(ClassWithGenericMiddle<>), nameof(ClassWithGenericMiddle<int>.Property2), nameof(ClassWithGenericMiddleBase));
+            AssertInvoker(typeof(ClassWithGenericMiddleChild), nameof(ClassWithGenericMiddleChild.Property3), nameof(ClassWithGenericMiddleBase));
+            
+            // Issue #516
+            AssertInvoker(typeof(ClassWithGenericParent<>), nameof(ClassWithGenericParent<int>.Property1), "ClassWithGenericParent`1<T>");
+            AssertInvoker(typeof(IntermediateGenericClass<>), nameof(IntermediateGenericClass<int>.Property2), "ClassWithGenericParent`1<T>");
+            AssertInvoker(typeof(ClassWithIntermediateGenericBase), nameof(ClassWithIntermediateGenericBase.Property3), "IntermediateGenericClass`1<System.String>");
```
Comment (ltrzesniewski) [inline Tests/AssemblyToProcessTests.cs]: Note: this really should be ``"ClassWithGenericParent`1<System.String>"`` instead of ``"IntermediateGenericClass`1<System.String>"`` but I wanted to fix the bad codegen ASAP.
